query getShippingEstimates($items: [SimulationItem], $postalCode: String, $country: String) {
  simulation(items: $items, postalCode: $postalCode, country: $country) {
    logisticsInfo {
      itemIndex
      slas {
        id
        name
        price
        shippingEstimate
        shippingEstimateDate
      }
    }
  }
}

