query Autocomplete($maxRows: Int, $inputValue: String) {
  autocomplete(maxRows: $maxRows, searchTerm: $inputValue) {
    itemsReturned {
      thumb
      name
      href
      productId
      criteria
      slug
    }
  }
}
